package com.example.attendee_university.service.impl;

import com.example.attendee_university.exception.BadRequestException;
import com.example.attendee_university.exception.NotFoundException;
import com.example.attendee_university.model.dto.holiday.request.HolidayRequest;
import com.example.attendee_university.model.dto.holiday.response.HolidayResponse;
import com.example.attendee_university.model.entity.AppUser;
import com.example.attendee_university.model.entity.GroupSession;
import com.example.attendee_university.model.entity.Holiday;
import com.example.attendee_university.repository.AppUserRepository;
import com.example.attendee_university.repository.GroupSessionRepository;
import com.example.attendee_university.repository.HolidayRepository;
import com.example.attendee_university.service.HolidayService;
import com.example.attendee_university.service.TimetableSlotService;
import com.example.attendee_university.utils.AppTimeZone;
import com.example.attendee_university.utils.HandleCurrentUser;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;
import java.util.List;
import java.util.Set;
import java.util.UUID;
import java.util.stream.Collectors;

@Slf4j
@Service
@RequiredArgsConstructor
public class HolidayServiceImpl implements HolidayService {

    private final HolidayRepository holidayRepository;
    private final GroupSessionRepository groupSessionRepository;
    private final AppUserRepository appUserRepository;
    private final TimetableSlotService timetableSlotService;
    private final HandleCurrentUser handleCurrentUser;

    @Override
    @Transactional
    public HolidayResponse createHoliday(HolidayRequest request) {
        if (holidayRepository.existsByDate(request.date())) {
            throw new BadRequestException("A holiday is already set for this date.");
        }

        UUID currentUserId = handleCurrentUser.getUserIdOfCurrentUser();

        Holiday holiday = Holiday.builder()
                .date(request.date())
                .name(request.name())
                .createdBy(currentUserId)
                .build();
        Holiday saved = holidayRepository.save(holiday);

        int affectedCount = cancelAndRescheduleFutureSessionsOn(request.date());

        log.info("Holiday created: {} on {} ({} already-scheduled session(s) cancelled and rescheduled)",
                saved.getName(), saved.getDate(), affectedCount);
        return toResponse(saved);
    }

    @Override
    public List<HolidayResponse> getAllHolidays() {
        return holidayRepository.findAllByOrderByDateAsc().stream()
                .map(this::toResponse)
                .toList();
    }

    @Override
    @Transactional
    public void deleteHoliday(UUID id) {
        Holiday holiday = holidayRepository.findById(id)
                .orElseThrow(() -> new NotFoundException("Holiday not found."));
        holidayRepository.delete(holiday);
        log.info("Holiday deleted: {} ({})", holiday.getName(), holiday.getDate());
        // Note: this does NOT retroactively re-insert a session on the now-unblocked
        // date — slots that already rescheduled past it stay where they landed.
        // Re-run generateSessions on the affected slot manually if you want it back.
    }

    // ── Helpers ────────────────────────────────────────────────
    // Cancels any already-generated, not-yet-started sessions that land on the given
    // date, then re-runs generation for each affected slot so its schedule extends by
    // one more occurrence to make up for the cancelled one — keeping totalSessions
    // meaning "this many real classes" even for holidays announced mid-semester.
    private int cancelAndRescheduleFutureSessionsOn(java.time.LocalDate date) {
        Instant dayStart = date.atStartOfDay(AppTimeZone.CAMBODIA).toInstant();
        Instant dayEnd = date.plusDays(1).atStartOfDay(AppTimeZone.CAMBODIA).toInstant();

        List<GroupSession> affected =
                groupSessionRepository.findFutureAutoGeneratedOnDate(dayStart, dayEnd, Instant.now());
        if (affected.isEmpty()) return 0;

        Set<UUID> affectedSlotIds = affected.stream()
                .map(GroupSession::getTimetableSlotId)
                .collect(Collectors.toSet());

        groupSessionRepository.deleteAll(affected);

        for (UUID slotId : affectedSlotIds) {
            try {
                timetableSlotService.generateSessions(slotId);
            } catch (Exception e) {
                log.warn("Could not auto-reschedule slot {} after new holiday on {}: {}", slotId, date, e.getMessage());
            }
        }

        return affected.size();
    }

    private HolidayResponse toResponse(Holiday holiday) {
        AppUser creator = appUserRepository.findById(holiday.getCreatedBy()).orElse(null);
        return HolidayResponse.builder()
                .id(holiday.getId())
                .date(holiday.getDate())
                .name(holiday.getName())
                .createdBy(holiday.getCreatedBy())
                .createdByName(creator != null ? creator.getName() : null)
                .createdAt(holiday.getCreatedAt())
                .build();
    }
}